### ISSUE TITLE
Forensic-logging-sidecar CircleCI builds are failing when using the latest Central-services-shared

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/forensic-logging-sidecar#12]
**Summary**:
Forensic-logging-sidecar CircleCI builds are failing when using the latest Central-services-shared:

Updated `package.json`:
```JSON
{
  "dependencies": {
    "@mojaloop/central-services-shared": "2.0.0-release"
  }
}
```

This results in a dependency failing to build as per the following
```
> node-rdkafka@2.4.1 install /home/circleci/project/node_modules/node-rdkafka
> node-gyp rebuild

gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
```
Due to a missing OS packages being installed (e.g. Python) which are required for `node-rdkafka` to correctly build.

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**
CircleCI builds should all pass successfully.

**Steps to Reproduce**
  1. Update the following dependency from `"@mojaloop/central-services-shared": "0.4.0` to `"@mojaloop/central-services-shared": "2.0.0-release"`
  1. Kick-off a CircleCI build with the update `package.json`

**Specifications**
  - Component: Forensic-logging-sidecar
  - Version: 2.0.0-snapshot
  - Platform: CircleCI
  - Subsystem: Continuous Integration/Builds scripts
  - Type of testing: CI Pipeline
  - Bug found/raised by: @johnschn05

**Notes**:

**Comment by elnyry-sam-k** [comment]
central-hub repo is now archived along with the current repo itself
